[tool.poetry]
name = "quest"
version = "0.1.0"
description = ""
authors = ["Anderson Andrade Silva <andersondrade@gmail.com>"]
license = "gnu"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
